### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by reinzor** [lg609/aubo_robot#1]
How to get started? What is the status? Is it usable yet?

Could you provide some kind of getting started like: http://wiki.ros.org/aubo_robot/Tutorials/Getting%20Started%20with%20a%20Aubo%20Robot

**Comment by zhaoyuRobotics** [comment]
@reinzor 

We are developing this tutorial, and you can temporarily refer to the start method of readme.md

**Comment by reinzor** [comment]
Hi @zhaoyuRobotics , thanks fo rthe update. However, I am currently not actively using the Aubo robot anymore. I will close the issue.
