### ISSUE TITLE
IKFast unable to run on aubo_i5.urdf

### ISSUE THREAD

**Issue by hhn1n15** [lg609/aubo_robot#23]
Hello, 

I am trying to use IKFast to generate inverse kinematics for my Aubo i5 v4 robot. However, when I used the .DAE file (converted from aubo_i5.urdf), IKFast cannot run. It reported zero determinant matrices. I was able to run IKFast on v2 robot from (https://github.com/auboliuxin/aubo_robot). Could you check if there is something wrong with the urdf file. Thanks!

**Comment by lg609** [comment]
We have checked the urdf file and find no problems.

**Comment by zhaoyuRobotics** [comment]
you can refer to this link:
https://github.com/yijiangh/Choreo/blob/7c98fd29120e5ce75d2b8ed17bc49488ad983cb6/framefab_robot/abb/framefab_irb6600/framefab_irb6600_support/doc/ikfast_tutorial.rst
