### ISSUE TITLE
aubo_control package can't catkin make successfully 

### ISSUE THREAD

**Issue by MRwangmaomao** [lg609/aubo_robot#30]
/usr/bin/ld: 找不到 -lindustrial_robot_client
collect2: error: ld returned 1 exit status
aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/build.make:122: recipe for target '/home/wpr/catkin_aubo/devel/lib/aubo_controller/aubo_joint_trajectory_action' failed
make[2]: *** [/home/wpr/catkin_aubo/devel/lib/aubo_controller/aubo_joint_trajectory_action] Error 1
CMakeFiles/Makefile2:5332: recipe for target 'aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/all' failed
make[1]: *** [aubo_robot/aubo_controller/CMakeFiles/aubo_joint_trajectory_action.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lg609** [comment]
if your ROS version is kinetic, try to install industrial_core package, like install apt-get install ros-kinetic-industrial-core. The framework is based on ROS-I.@MRwangmaomao
