### ISSUE TITLE
关于 catkin_make 显示报错问题

### ISSUE THREAD

**Issue by super-dashuaibi** [lg609/aubo_robot#97]
你好  我在工作空间myaubo下 进行catkin_make时候（前面安装moveit 和 industrial_core都没问题）,会显示如下错误：
/usr/bin/ld: warning: libprotobuf.so.9, needed by /home/mango/myaubo/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller/libauborobotcontroller.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /home/mango/myaubo/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller/libauborobotcontroller.so: undefined reference to `vtable for google::protobuf::MessageLite'
/usr/bin/ld: /home/mango/myaubo/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller/libauborobotcontroller.so: undefined reference to `google::protobuf::MessageLite::ParseFromArray(void const*, int)'
/usr/bin/ld: /home/mango/myaubo/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller/libauborobotcontroller.so: undefined reference to `google::protobuf::internal::WireFormat::SkipField(google::protobuf::io::CodedInputStream*, unsigned int, google::protobuf::UnknownFieldSet*)'
。。。。
。。。。（省略很多行）
/usr/bin/ld: /home/mango/myaubo/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller/libauborobotcontroller.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteFloat(int, float, google::protobuf::io::CodedOutputStream*)'
/usr/bin/ld: /home/mango/myaubo/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller/libauborobotcontroller.so: undefined reference to `google::protobuf::internal::RepeatedPtrFieldBase::Reserve(int)'
/usr/bin/ld: /home/mango/myaubo/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller/libauborobotcontroller.so: undefined reference to `google::protobuf::io::CodedInputStream::PushLimit(int)'
/usr/bin/ld: /home/mango/myaubo/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller/libauborobotcontroller.so: undefined reference to `google::protobuf::internal::LogMessage::operator<<(char const*)'
/usr/bin/ld: /home/mango/myaubo/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller/libauborobotcontroller.so: undefined reference to `google::protobuf::internal::WireFormat::SerializeUnknownFields(google::protobuf::UnknownFieldSet const&, google::protobuf::io::CodedOutputStream*)'
collect2: error: ld returned 1 exit status
make[2]: *** [aubo_robot/aubo_driver/CMakeFiles/testAuboAPI.dir/build.make:101：/home/mango/myaubo/devel/lib/aubo_driver/testAuboAPI] 错误 1
make[1]: *** [CMakeFiles/Makefile2:4707：aubo_robot/aubo_driver/CMakeFiles/testAuboAPI.dir/all] 错误 2

然后我已经重新装过protobuf了  目前我的版本是：
Ubuntu 20.04 

Ros  Noetic

gcc (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

protoc  libprotoc 28.0-dev

**Comment by Joinjiang** [comment]
The new format of libauborobotcontroller link is wrong. you can repalce aubocontroller folder by old.

**Comment by Joinjiang** [comment]
the libauborobotcontroller.so is wrong format in ubuntu. it must update the new file

**Comment by Liu-Rrr** [comment]
> the libauborobotcontroller.so is wrong format in ubuntu. it must update the new file

It seems that only publishers can update, and I tried to copy the previous version

**Comment by Joinjiang** [comment]
you are right, and it is work using previous version

**Comment by Joinjiang** [comment]
> 
> 
> 
> 
> > the libauborobotcontroller.so is wrong format in ubuntu. it must update the new file
> 
> It seems that only publishers can update, and I tried to copy the previous version

you are right, and it is work using previous version

**Comment by Liu-Rrr** [comment]
> > > the libauborobotcontroller.so is wrong format in ubuntu. it must update the new file
> > 
> > 
> > It seems that only publishers can update, and I tried to copy the previous version
> 
> you are right, and it is work using previous version

do you have any joint jams when controlling the physical robot arm？

**Comment by Joinjiang** [comment]
> > > > the libauborobotcontroller.so is wrong format in ubuntu. it must update the new file
> > > 
> > > 
> > > It seems that only publishers can update, and I tried to copy the previous version
> > 
> > you are right, and it is work using previous version
> 
> do you have any joint jams when controlling the physical robot arm？
using this new version? have joint jams?

**Comment by Liu-Rrr** [comment]
sorry, what I want to express is that the movement of the previous or this version of the physical robot arm felt a little slow and loud

> > > > > the libauborobotcontroller.so is wrong format in ubuntu. it must update the new file
> > > > 
> > > > 
> > > > It seems that only publishers can update, and I tried to copy the previous version
> > > 
> > > 
> > > you are right, and it is work using previous version
> > 
> > 
> > do you have any joint jams when controlling the physical robot arm？
> > using this new version? have joint jams?

sorry, what I want to express is that the movement of the previous or this version of the physical robot arm felt a little slow and loud

**Comment by Joinjiang** [comment]
> sorry, what I want to express is that the movement of the previous or this version of the physical robot arm felt a little slow and loud
> 
> > > > > > the libauborobotcontroller.so is wrong format in ubuntu. it must update the new file
> > > > > 
> > > > > 
> > > > > It seems that only publishers can update, and I tried to copy the previous version
> > > > 
> > > > 
> > > > you are right, and it is work using previous version
> > > 
> > > 
> > > do you have any joint jams when controlling the physical robot arm？
> > > using this new version? have joint jams?
> 
> sorry, what I want to express is that the movement of the previous or this version of the physical robot arm felt a little slow and loud

yes, certainly. you can improve its velocity. but it may be shacked sometimes

**Comment by 2024Me336Spring** [comment]
Hello, I tried catkin_make and catkin build. Both of the method lead to **'libauborobotcontroller.so: file format not recognized; treating as linker script` `libauborobotcontroller.so:0: syntax error`.** 
And I used "file" to check the format of libauborobotcontroller.so, it turned out to be **ASCII**, which is wrong.
The possible reason is that some library files, when decompressed in a Windows environment and then transferred to a Linux environment. 
Hope the  publishers  @HysteriaC  can fix this soon.

**Comment by Liu-Rrr** [comment]
> Hello, I tried catkin_make and catkin build. Both of the method lead to **'libauborobotcontroller.so: file format not recognized; treating as linker script` `libauborobotcontroller.so:0: syntax error`.** And I used "file" to check the format of libauborobotcontroller.so, it turned out to be **ASCII**, which is wrong. The possible reason is that some library files, when decompressed in a Windows environment and then transferred to a Linux environment. Hope the publishers @HysteriaC can fix this soon.

the publishers should upload the wrong format, you can replace it with the previous version of libauborobotcontroller multiple so files

**Comment by 2024Me336Spring** [comment]
> > Hello, I tried catkin_make and catkin build. Both of the method lead to **'libauborobotcontroller.so: file format not recognized; treating as linker script` `libauborobotcontroller.so:0: syntax error`.** And I used "file" to check the format of libauborobotcontroller.so, it turned out to be **ASCII**, which is wrong. The possible reason is that some library files, when decompressed in a Windows environment and then transferred to a Linux environment. Hope the publishers @HysteriaC can fix this soon.
> 
> the publishers should upload the wrong format, you can replace it with the previous version of libauborobotcontroller multiple so files

Hello, could you tell me which previous veision should I choose? Thanks a lot.

**Comment by Liu-Rrr** [comment]
> > > Hello, I tried catkin_make and catkin build. Both of the method lead to **'libauborobotcontroller.so: file format not recognized; treating as linker script` `libauborobotcontroller.so:0: syntax error`.** And I used "file" to check the format of libauborobotcontroller.so, it turned out to be **ASCII**, which is wrong. The possible reason is that some library files, when decompressed in a Windows environment and then transferred to a Linux environment. Hope the publishers @HysteriaC can fix this soon.
> > 
> > 
> > the publishers should upload the wrong format, you can replace it with the previous version of libauborobotcontroller multiple so files
> 
> Hello, could you tell me which previous veision should I choose? Thanks a lot.

144320024 in commit

**Comment by HysteriaC** [comment]
> > Hello, I tried catkin_make and catkin build. Both of the method lead to **'libauborobotcontroller.so: file format not recognized; treating as linker script` `libauborobotcontroller.so:0: syntax error`.** And I used "file" to check the format of libauborobotcontroller.so, it turned out to be **ASCII**, which is wrong. The possible reason is that some library files, when decompressed in a Windows environment and then transferred to a Linux environment. Hope the publishers @HysteriaC can fix this soon.
> 
> the publishers should upload the wrong format, you can replace it with the previous version of libauborobotcontroller multiple so files

thanks for ur questions ,i have already noted about this issue.i will update&pull up new .gitattributes for ensure “.so”files format was correctly when gitting package at nearly future.
currently, you can git the "aubo_driver/lib" files from the master branch and replace the old files for "catkin_make" . make sure the files was binary files.
also u can use those code below manually restore those symbolic links. (at your`/src/aubo_robot/aubo_driver/lib/lib64/aubocontroller` directory.)

`ln -sf libauborobotcontroller.so.1.3.1 libauborobotcontroller.so`
`ln -sf libauborobotcontroller.so.1.3.1 libauborobotcontroller.so.1`
`ln -sf libauborobotcontroller.so.1.3.1 libauborobotcontroller.so.1.3`
